default_model_import_path: src.ray.deployments.model:app
request_import_path: src.ray.deployments.request:app
request_num_replicas: 1
models:
  # - model_key: 'nnsight.models.LanguageModel.LanguageModel:{"repo_id": "openai-community/gpt2"}'
  #   num_replicas: 1
  #   ray_actor_options:
  #     resources:
  #       cuda_memory_MB: 15000


  - model_key: 'nnsight.models.LanguageModel.LanguageModel:{"repo_id": "meta-llama/Meta-Llama-3-8B"}'
    num_replicas: 1
    model_import_path: src.ray.deployments.distributed_model:app
    args:
      torch_distributed_port: 5003
      torch_distributed_world_size: 2
      torch_distributed_world_timeout_seconds: 40
      tensor_parallelism_size: 2
    ray_actor_options:
      num_gpus: 1


  # - model_key: 'nnsight.models.LanguageModel.LanguageModel:{"repo_id": "meta-llama/Meta-Llama-3-8B"}'
  #   num_replicas: 1
    
  #   ray_actor_options:
  #     num_gpus: 1