channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - git
  - pip:
    - pip
    - setuptools
    # Install PyTorch with CUDA support first (before nnsight which depends on it)
    - torch --index-url https://download.pytorch.org/whl/cu128
    - nnsight
    - ray[serve]==2.47.0
    - python-slugify
    # Telemetry
    - prometheus_client
    - python-logging-loki
    # Database
    - boto3
    - influxdb-client
    # Google Cal Scheduling
    - google-api-python-client
    - google
