channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - pip
    - setuptools
    - nnsight>=0.5.0
    - ray[serve]==2.47.0
    - python-slugify
    # Telemetry
    - prometheus_client
    - python-logging-loki
    # Database
    - boto3
    - influxdb-client
    # Google Cal Scheduling
    - google-api-python-client
    - google
