version: '3'
services:
  ray-worker:
    image: ray_worker:latest
    volumes:
      - /drive7/hf-cache/hub/:/root/.cache/huggingface/hub
    network_mode: "host"
    environment:
      RAY_ADDRESS: 127.0.0.1:6379
      INFLUXDB_ADDRESS: http://${HOST_IP}:${DEV_INFLUXDB_PORT}
      INFLUXDB_ADMIN_TOKEN: ${SECRET_INFLUXDB_ADMIN_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [ gpu ]
