services:

  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672

  minio:
    image: minio/minio:latest
    command: server /data
    # environment:
    #   - MINIO_ACCESS_KEY=minioadmin
    #     MINIO_SECRET_KEY=minioadmin
    ports:
      - 27017:9000

  ray-head:
    image: ray_head:latest
    network_mode: "host"
    shm_size: '15gb'
    volumes:
      - /disk/u/jfiottok/.cache/huggingface/hub/:/root/.cache/huggingface/hub
      - /share/u/ndif/ndif-deployment/ndif/compose/prod/service_config.yml:/src/ray/config/service_config.yml
      - /share/u/ndif/ndif-deployment/ndif/compose/prod/ray_config.yml:/src/ray/config/ray_config.yml
      - /share/u/ndif/ndif-deployment/ndif/compose/prod/ray-head-start.sh:/start.sh
      - ray-data:/tmp/ray/
    environment:
      NCCL_DEBUG: INFO
      LOKI_URL: http://nagoya.research.khoury.northeastern.edu:3100/loki/api/v1/push
      OBJECT_STORE_URL: nagoya.research.khoury.northeastern.edu:27017
      API_URL: https://ndif.dev
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [ gpu ]

  api:
    depends_on:
      - rabbitmq
      - ray-head
      - minio
    image: api:latest
    ports:
      - 5000:80
    volumes:
      - /disk/u/jfiottok/wd/ndif/compose/prod/api-start.sh:/start.sh
    environment:
      OBJECT_STORE_URL: nagoya.research.khoury.northeastern.edu:27017
      RMQ_URL: amqp://guest:guest@nagoya.research.khoury.northeastern.edu:5672/
      WORKERS: 12
      RAY_ADDRESS: ray://nagoya.research.khoury.northeastern.edu:10001
      LOKI_URL: http://nagoya.research.khoury.northeastern.edu:3100/loki/api/v1/push
      FIREBASE_CREDS_PATH: /src/creds.json  
  
  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - prometheus-data:/prometheus
      - ../../telemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ray-data:/tmp/ray
    depends_on:
      - api
      - ray-head

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../../telemetry/grafana/provisioning:/etc/grafana/provisioning
      - ../../telemetry/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.8.1
    network_mode: "host"
    volumes:
      - loki-data:/loki

volumes:
  grafana-storage:
  loki-data:
  prometheus-data:
  ray-data:
