version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672

  minio:
    image: minio/minio:latest
    command: server /data
    # environment:
    #   - MINIO_ACCESS_KEY=minioadmin
    #     MINIO_SECRET_KEY=minioadmin
    ports:
      - 27017:9000

  ray-head:
    image: ray_head:latest
    network_mode: "host"
    shm_size: '15gb'
    volumes:
      - /disk/u/jfiottok/.cache/huggingface/hub/:/root/.cache/huggingface/hub
      - /disk/u/jfiottok/wd/ndif/compose/prod/service_config.yml:/src/ray/config/service_config.yml
      - /disk/u/jfiottok/wd/ndif/compose/prod/ray_config.yml:/src/ray/config/ray_config.yml
      - /disk/u/jfiottok/wd/ndif/compose/prod/ray-head-start.sh:/start.sh
    
    environment:
      NCCL_DEBUG: INFO
      # RAY_SERVE_QUEUE_LENGTH_RESPONSE_DEADLINE_S: 20
      # RAY_health_check_initial_delay_ms: 600000
      # RAY_health_check_period_ms: 600000
      # RAY_num_heartbeats_timeout: 300
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [ gpu ]

  api:
    depends_on:
      - rabbitmq
      - ray-head
      - minio
    image: api:latest
    ports:
      - 5000:80
    environment:
      OBJECT_STORE_URL: nagoya.research.khoury.northeastern.edu:27017
      RMQ_URL: amqp://guest:guest@nagoya.research.khoury.northeastern.edu:5672/
      WORKERS: 12
      RAY_ADDRESS: ray://nagoya.research.khoury.northeastern.edu:10001
      FIREBASE_CREDS_PATH: /src/creds.json
