version: '3'
services:

  api:
    image: api:latest
    ports:
    # 5002 for delta 405b users
      - 5002:80
    environment:
      DATABASE_URL: mongodb://user:pass@nagoya.research.khoury.northeastern.edu:27017
      RMQ_URL: amqp://guest:guest@nagoya.research.khoury.northeastern.edu:5672/
      WORKERS: 12
      # delta port forwarding ray address
      RAY_ADDRESS: ray://nagoya.research.khoury.northeastern.edu:9999
      FIREBASE_CREDS_PATH: /src/creds.json
