services:
  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${DEV_RABBITMQ_PORT}:5672

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - ${DEV_MINIO_PORT}:9000
  ray-head:
    image: ray_head:latest
    shm_size: '15gb'
    volumes:
      - ~/.cache/huggingface/hub/:/root/.cache/huggingface/hub
      - ./service_config.yml:/src/ray/config/service_config.yml
      - ./ray_config.yml:/src/ray/config/ray_config.yml
      - ./ray-head-start.sh:/start.sh
      - ray-data:/tmp/ray/
    ports:
      - ${DEV_RAY_HEAD_PORT}:6379
      - 9998:10001
      - ${DEV_RAY_DASHBOARD_PORT}:8265
      - ${DEV_RAY_SERVE_PORT}:8267
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${N_DEVICES}
              capabilities: [ gpu ]

    environment:
      - RAY_METRICS_GAUGE_EXPORT_INTERVAL_MS=1000
      - LOKI_URL=http://${HOST_IP}:${DEV_LOKI_PORT}/loki/api/v1/push
      - OBJECT_STORE_URL=${HOST_IP}:${DEV_MINIO_PORT}
      - API_URL=http://${HOST_IP}:${DEV_API_PORT}
  api:
    image: api:latest
    ports:
      - ${DEV_API_PORT}:80
    environment:
      OBJECT_STORE_URL: ${HOST_IP}:${DEV_MINIO_PORT}
      RMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${HOST_IP}:${DEV_RABBITMQ_PORT}/
      WORKERS: 1
      RAY_ADDRESS: ray://${HOST_IP}:9998
      LOKI_URL: http://${HOST_IP}:${DEV_LOKI_PORT}/loki/api/v1/push

  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - prometheus-data:/prometheus
      - ../../telemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ray-data:/tmp/ray
    depends_on:
      - api
      - ray-head

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../../telemetry/grafana/provisioning:/etc/grafana/provisioning
      - ../../telemetry/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.8.1
    network_mode: "host"
    volumes:
      - loki-data:/loki

volumes:
  grafana-storage:
  loki-data:
  prometheus-data:
  ray-data: