version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5673:5672

  minio:
    image: minio/minio:latest
    ports:
      - 27018:9000

  ray-head:
    image: ray_head:latest
    shm_size: '15gb'
    volumes:
      - /share/u/jadenfk/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - ray-data:/tmp/ray/session_latest
      - /disk/u/jfiottok/.cache/huggingface/hub/:/root/.cache/huggingface/hub
      - /disk/u/jfiottok/wd/ndif/compose/prod/service_config.yml:/src/ray/config/service_config.yml
      - /disk/u/jfiottok/wd/ndif/compose/prod/ray_config.yml:/src/ray/config/ray_config.yml
      - /disk/u/jfiottok/wd/ndif/compose/prod/ray-head-start.sh:/start.sh
    
    ports:
      - 6380:6379
      - 9998:10001
      - 8266:8265
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [ gpu ]
    environment:
       - OBJECT_STORE_URL=localhost:27017
       - RAY_METRICS_EXPORT_PORT=8267
       - RAY_JOB_METRICS_EXPORT_PORT=8267
       - RAY_METRICS_GAUGE_EXPORT_INTERVAL_MS=1000
       - LOKI_URL=http://localhost:3100/loki/api/v1/push

  api:
    image: api:latest
    network_mode: "host"
    environment:
      OBJECT_STORE_URL: localhost:27017
      RMQ_URL: amqp://guest:guest@localhost:5672/
      WORKERS: 1
      RAY_ADDRESS: ray://localhost:10001
      LOKI_URL: http://localhost:3100/loki/api/v1/push
      # FIREBASE_CREDS_PATH

  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - prometheus-data:/prometheus
      - ../../telemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
      - ray-head

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.8.1
    network_mode: "host"
    volumes:
      - loki-data:/loki

volumes:
  grafana-storage:
  loki-data:
  prometheus-data:
  ray-data:
