services:

  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5673:5672

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - 27018:9000

  ray-head:
    image: ray_head:latest
    shm_size: '15gb'
    volumes:
      - ~/.cache/huggingface/hub/:/root/.cache/huggingface/hub
      - ./service_config.yml:/src/ray/config/service_config.yml
      - ./ray_config.yml:/src/ray/config/ray_config.yml
      - ./ray-head-start.sh:/start.sh
      - ray-data:/tmp/ray/session_latest
    ports:
      - 6380:6379
      - 9998:10001
      - 8266:8265
      - 8267:8267
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${N_DEVICES}
              capabilities: [ gpu ]

    environment:
      - RAY_METRICS_GAUGE_EXPORT_INTERVAL_MS=1000
      - LOKI_URL=http://${HOST_IP}:3100/loki/api/v1/push
      - OBJECT_STORE_URL=${HOST_IP}:27018
      - API_URL=http://${HOST_IP}:5001

  api:
    image: api:latest
    ports:
      - 5001:80
    environment:
      OBJECT_STORE_URL: ${HOST_IP}:27018
      RMQ_URL: amqp://guest:guest@${HOST_IP}:5673/
      WORKERS: 1
      RAY_ADDRESS: ray://${HOST_IP}:9998
      LOKI_URL: http://${HOST_IP}:3100/loki/api/v1/push
      # FIREBASE_CREDS_PATH

  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - prometheus-data:/prometheus
      - ../../telemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
      - ray-head

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../../telemetry/grafana/provisioning:/etc/grafana/provisioning
      - ../../telemetry/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.8.1
    network_mode: "host"
    volumes:
      - loki-data:/loki

volumes:
  grafana-storage:
  loki-data:
  prometheus-data:
  ray-data:
