global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'combined_metrics'
    static_configs:
      - targets: 
        - localhost:8267  # Ray
        - localhost:80    # FastAPI
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'ray_request_status'
        target_label: __name__
        replacement: 'request_status'
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*:(8267|80)'
        replacement: '${1}'
        target_label: job
        action: replace
      - source_labels: [job]
        regex: '8267'
        replacement: 'ray'
        target_label: job
      - source_labels: [job]
        regex: '80'
        replacement: 'fast_api'
        target_label: job